name: CI Rails tests (Lab 3)
on: [push, pull_request]
env:
  RUBY_VERSION: 3.4.5
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password
  NODE_VERSION: 16

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest

    services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    options: >-
      --health-cmd "pg_isready -U postgres"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5


    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install PostgreSQL client
        run: sudo apt-get install -y libpq-dev

      - name: Install Ruby gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install Yarn dependencies
        run: yarn install

      - name: Setup database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Run Brakeman
        run: brakeman -o brakeman.txt

      - name: Run RuboCop
        run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload RuboCop report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: rubocop-report
          path: rubocop.txt

      - name: Upload Brakeman report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: brakeman-report
          path: brakeman.txt
